### ISSUE TITLE
Remove velocity override code (pushMotion)

### ISSUE THREAD

**Issue by marshallpowell97** [ros-industrial/staubli_val3_driver#1] opened 2020-01-10 18:23 UTC
https://github.com/ros-industrial/staubli_val3_driver/blob/55b4fe6d3fbc60fa7a89139aa0f195c5d3c62072/staubli_val3_driver/val3/ros_server/pushMotion.pgx#L72-L79

Sets the velocity to the value set on the teach pendant if 'velocity override' is enabled. This does not seem to work as intended since the velocity set on the pendant already "overrides" whatever value is set in the Val3 code. The result is that the "overridden" velocity ends up being much smaller than intended.

I.E. if 50% velocity is set by the pendant, the actual speed of the robot will be 50% (result from `getMonitorSpeed()` ) multiplied by another 50% (set by the pendant) = 25%

**Comment by gavanderhoorn** [comment] 2020-03-12 11:05
As I wrote in https://github.com/ros-industrial/staubli_val3_driver/pull/8#discussion_r369798953, I believe it'd be best to remove the override: it reportedly doesn't work as intended.

I'll change the title of this issue to convert it into an action item.

**Comment by marshallpowell97** [comment] 2020-03-12 13:59
I have this removed in a branch [here](https://github.com/marshallpowell97/staubli_val3_driver/tree/removeVelOverwrite) ready to make a pull request whenever the previous one is approved.

**Comment by gavanderhoorn** [comment] 2020-03-12 14:28
It would probably be good to rebase your new branch once #8 gets merged.

**Comment by gavanderhoorn** [comment] 2020-03-30 12:42
I've linked this to #9, as it (starts to) remove(s) the velocity override.

**Comment by gavanderhoorn** [comment] 2020-03-30 12:43
Seeing issues like #2 (and the attempts to fix this in #8 and then #18), perhaps the rationale behind the velocity override functionality was exactly the problems we're encountering now?

**Closed** 2020-06-09 18:34 UTC
Labels: enhancement, good first issue
